version: '3'
services:
  retriever:
    build: .
    volumes:
      - .:/usr/src/app
    env_file: ./.env
    environment:
      - MONGO_HOST=mongodb://mongo:27017
      - MONGO_USER=
      - MONGO_PASS=
  mongo:
    image: mongo
    volumes:
      - healthworkers:/data/db
    ports:
      - "27017:27017"
volumes:
  healthworkers:
